### ISSUE TITLE
Fire IE 0.4.5.2 in Firefox 64 bit and IE11 

### ISSUE THREAD

**Issue by olkba** [yxl/Fire-IE#183]
Hello, when I start FF I got message Fire IE plugin is not installed -but it is I tried also manual download from your page - and when I switch tab to show as in IE I got message A plugin is needed to display this contect.
Thank you for your help.
If it was already answered I didn't find it ;-(

**Comment by patwonder** [comment]
Due to https://bugzilla.mozilla.org/show_bug.cgi?id=1165981, Mozilla has disabled all plugins except Adobe Flash in the official x64 version, which breaks Fire IE.

@xunxun1982 has developed a binary patch tool that can remove the plugin restriction. You can download it from the following URL:
* For Firefox 41 through 44: http://sourceforge.net/projects/pcxfirefox/files/Tools/RemoveFx41x64PluginRestrict/patch4fx41x64-en-20150904.7z/download
* For Firefox 45+: http://sourceforge.net/projects/pcxfirefox/files/Tools/RemoveFx41x64PluginRestrict/patch4fx45x64-20151231.7z/download
